name = "zai-telegram-bot"
compatibility_date = "2025-08-06"
main = "worker.js"

[vars]
TELEGRAM_BOT_TOKEN = "8285384768:AAGXNkTZfGm4OqyDqPEV3AQR9brWC0U2GNo"
GEMINI_API_KEY = "AIzaSyAw4ZI1o4qSIqBYmi2Eti96_kJsqJFVNWE"
