name = "zai-telegram-bot"
compatibility_date = "2025-08-06"
main = "worker.js"

kv_namespaces = [
  { binding = "BOT_CACHE", id = "112ccdc301c24882819fdc5352becfa0" }
]

[vars]
TELEGRAM_BOT_TOKEN = "6559421973:AAFKDg5Ah7xPafoEqX-9QWN_7g2G7OTbGtc"
GEMINI_API_KEY = "AIzaSyAOTo2TSBOppV7ez8NlXKJWrJSOkeizkss"
TELEGRAM_BOT_USERNAME = "suichan_ai_bot" 

[observability.logs]
enabled = true
