name = "zai-telegram-bot"
compatibility_date = "2025-08-06"
main = "worker.js"

kv_namespaces = [
  { binding = "BOT_CACHE", id = "112ccdc301c24882819fdc5352becfa0" }
]

[vars]
TELEGRAM_BOT_TOKEN = "6559421973:AAHuMKAaq_ZdvyWnDgzWjlzi9B9zBMJxAOw"
ZHIPUAI_API_KEY = "93bf2ce436a144bb8f14061458cef55b.waBULwb6TvCHymvy"
TELEGRAM_BOT_USERNAME = "suichan_ai_bot"  


[observability.logs]
enabled = true
