name = "zai-telegram-bot"
compatibility_date = "2025-08-06"
main = "worker.js"

kv_namespaces = [
  { binding = "BOT_CACHE", id = "112ccdc301c24882819fdc5352becfa0" }
]

[vars]
TELEGRAM_BOT_TOKEN = "8285384768:AAFiWdICSWyAH3w6CqHtb8akZSn0RZj_vRM"
GEMINI_API_KEY = "AIzaSyAOTo2TSBOppV7ez8NlXKJWrJSOkeizkss"
TELEGRAM_BOT_USERNAME = "Chat_zAI_bot" 

[observability.logs]
enabled = true
